"""create_all_tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-18

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('topic', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='content'
    )
    op.create_index('idx_sources_provider_kind', 'sources', ['provider', 'kind'], unique=False, schema='content')
    op.create_table('feature_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled_globally', sa.Boolean(), nullable=False),
    sa.Column('rollout_percent', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_feature_flags_key'), 'feature_flags', ['key'], unique=True, schema='core')
    op.create_table('households',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_users_email'), 'users', ['email'], unique=True, schema='core')
    op.create_table('ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('default_unit', sa.String(length=32), nullable=True),
    sa.Column('typical_shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name'),
    schema='food'
    )
    op.create_index('idx_ingredients_canonical', 'ingredients', ['canonical_name'], unique=False, schema='food')
    op.create_table('badge_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tracking'
    )
    op.create_index(op.f('ix_tracking_badge_definitions_key'), 'badge_definitions', ['key'], unique=True, schema='tracking')
    op.create_table('briefings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('for_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=True),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('delivered_via', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('was_read', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index('idx_briefings_household_date', 'briefings', ['household_id', 'for_date'], unique=True, schema='ai')
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('surface', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index('idx_conversations_household_recent', 'conversations', ['household_id', 'updated_at'], unique=False, schema='ai')
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_seen', sa.Integer(), nullable=False),
    sa.Column('items_inserted', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['content.sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='content'
    )
    op.create_index('idx_ingestion_jobs_status_started', 'ingestion_jobs', ['status', 'started_at'], unique=False, schema='content')
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('topic', sa.String(length=32), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('derived_recipe_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['content.sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='content'
    )
    op.create_index('idx_items_provider_external', 'items', ['provider', 'external_id'], unique=True, schema='content')
    op.create_index('idx_items_source', 'items', ['source_id'], unique=False, schema='content')
    op.create_index('idx_items_topic_published', 'items', ['topic', 'published_at'], unique=False, schema='content')
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_events_entity', 'events', ['entity_type', 'entity_id'], unique=False, schema='core')
    op.create_index('idx_events_household', 'events', ['household_id', 'created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_events_event_type'), 'events', ['event_type'], unique=False, schema='core')
    op.create_table('household_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('invite_email', sa.String(length=320), nullable=True),
    sa.Column('invite_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_household_members_user', 'household_members', ['user_id'], unique=False, schema='core')
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tier_a_enabled', sa.Boolean(), nullable=False),
    sa.Column('tier_s_enabled', sa.Boolean(), nullable=False),
    sa.Column('tier_b_enabled', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renews_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='core'
    )
    op.create_table('meal_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('target_budget_usd', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='food'
    )
    op.create_index(op.f('ix_food_meal_plans_household_id'), 'meal_plans', ['household_id'], unique=False, schema='food')
    op.create_table('pantry_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location_type', sa.String(length=32), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='food'
    )
    op.create_index(op.f('ix_food_pantry_locations_household_id'), 'pantry_locations', ['household_id'], unique=False, schema='food')
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('store_name', sa.String(length=200), nullable=True),
    sa.Column('purchased_at', sa.Date(), nullable=True),
    sa.Column('subtotal_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('parse_status', sa.String(length=16), nullable=False),
    sa.Column('parse_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='food'
    )
    op.create_index('idx_receipts_household_date', 'receipts', ['household_id', 'purchased_at'], unique=False, schema='food')
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_attribution', sa.String(length=200), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('prep_time_min', sa.Integer(), nullable=True),
    sa.Column('cook_time_min', sa.Integer(), nullable=True),
    sa.Column('cuisine', sa.String(length=64), nullable=True),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('estimated_cost_per_serving_usd', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_user_created', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('imported_from_content_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='food'
    )
    op.create_index(op.f('ix_food_recipes_cuisine'), 'recipes', ['cuisine'], unique=False, schema='food')
    op.create_table('badge_awards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('badge_definition_id', sa.UUID(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['badge_definition_id'], ['tracking.badge_definitions.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tracking'
    )
    op.create_index('idx_badge_awards_household', 'badge_awards', ['household_id'], unique=False, schema='tracking')
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('month_start', sa.Date(), nullable=False),
    sa.Column('target_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tracking'
    )
    op.create_index('idx_budgets_household_month', 'budgets', ['household_id', 'month_start'], unique=False, schema='tracking')
    op.create_table('savings_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_on', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('source_entity_type', sa.String(length=32), nullable=True),
    sa.Column('source_entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tracking'
    )
    op.create_index('idx_savings_household_date', 'savings_events', ['household_id', 'occurred_on'], unique=False, schema='tracking')
    op.create_index('idx_savings_kind', 'savings_events', ['kind'], unique=False, schema='tracking')
    op.create_table('spend_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('spent_on', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_entity_type', sa.String(length=32), nullable=True),
    sa.Column('source_entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tracking'
    )
    op.create_index('idx_spend_household_date', 'spend_entries', ['household_id', 'spent_on'], unique=False, schema='tracking')
    op.create_index(op.f('ix_tracking_spend_entries_category'), 'spend_entries', ['category'], unique=False, schema='tracking')
    op.create_table('streaks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('current_length', sa.Integer(), nullable=False),
    sa.Column('longest_length', sa.Integer(), nullable=False),
    sa.Column('last_event_on', sa.Date(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tracking'
    )
    op.create_index('idx_streaks_household_kind', 'streaks', ['household_id', 'kind'], unique=True, schema='tracking')
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai.conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index('idx_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False, schema='ai')
    op.create_table('voice_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('wake_phrase', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai.conversations.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_voice_sessions_household_id'), 'voice_sessions', ['household_id'], unique=False, schema='ai')
    op.create_table('bookmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['content.items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='content'
    )
    op.create_index('idx_bookmarks_household', 'bookmarks', ['household_id'], unique=False, schema='content')
    op.create_table('pantry_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.Column('raw_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('purchased_at', sa.Date(), nullable=True),
    sa.Column('opened_at', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['food.ingredients.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['food.pantry_locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='food'
    )
    op.create_index('idx_pantry_household_expires', 'pantry_items', ['household_id', 'expires_at'], unique=False, schema='food')
    op.create_index('idx_pantry_ingredient', 'pantry_items', ['ingredient_id'], unique=False, schema='food')
    op.create_table('planned_meals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_plan_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=16), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['food.meal_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['food.recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='food'
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.Column('raw_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('substitutions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['food.ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['food.recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='food'
    )
    op.create_table('recipe_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['food.recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='food'
    )
    op.create_table('shopping_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('meal_plan_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['food.meal_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='food'
    )
    op.create_index(op.f('ix_food_shopping_lists_household_id'), 'shopping_lists', ['household_id'], unique=False, schema='food')
    op.create_table('food_waste_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('pantry_item_id', sa.UUID(), nullable=True),
    sa.Column('ingredient_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('estimated_value_usd', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('occurred_on', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.ForeignKeyConstraint(['pantry_item_id'], ['food.pantry_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='food'
    )
    op.create_index(op.f('ix_food_food_waste_events_household_id'), 'food_waste_events', ['household_id'], unique=False, schema='food')
    op.create_table('preservation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('source_pantry_item_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('ingredient_name', sa.String(length=200), nullable=False),
    sa.Column('quantity_in', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('quantity_out', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('storage_location_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('safety_check_passed', sa.Boolean(), nullable=False),
    sa.Column('safety_notes', sa.Text(), nullable=True),
    sa.Column('photo_urls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['core.households.id'], ),
    sa.ForeignKeyConstraint(['source_pantry_item_id'], ['food.pantry_items.id'], ),
    sa.ForeignKeyConstraint(['storage_location_id'], ['food.pantry_locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='food'
    )
    op.create_index(op.f('ix_food_preservation_jobs_household_id'), 'preservation_jobs', ['household_id'], unique=False, schema='food')
    op.create_table('shopping_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shopping_list_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.Column('raw_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('store', sa.String(length=120), nullable=True),
    sa.Column('estimated_price_usd', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('actual_price_usd', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['food.ingredients.id'], ),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['food.shopping_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='food'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_items', schema='food')
    op.drop_index(op.f('ix_food_preservation_jobs_household_id'), table_name='preservation_jobs', schema='food')
    op.drop_table('preservation_jobs', schema='food')
    op.drop_index(op.f('ix_food_food_waste_events_household_id'), table_name='food_waste_events', schema='food')
    op.drop_table('food_waste_events', schema='food')
    op.drop_index(op.f('ix_food_shopping_lists_household_id'), table_name='shopping_lists', schema='food')
    op.drop_table('shopping_lists', schema='food')
    op.drop_table('recipe_steps', schema='food')
    op.drop_table('recipe_ingredients', schema='food')
    op.drop_table('planned_meals', schema='food')
    op.drop_index('idx_pantry_ingredient', table_name='pantry_items', schema='food')
    op.drop_index('idx_pantry_household_expires', table_name='pantry_items', schema='food')
    op.drop_table('pantry_items', schema='food')
    op.drop_index('idx_bookmarks_household', table_name='bookmarks', schema='content')
    op.drop_table('bookmarks', schema='content')
    op.drop_index(op.f('ix_ai_voice_sessions_household_id'), table_name='voice_sessions', schema='ai')
    op.drop_table('voice_sessions', schema='ai')
    op.drop_index('idx_messages_conversation_created', table_name='messages', schema='ai')
    op.drop_table('messages', schema='ai')
    op.drop_index('idx_streaks_household_kind', table_name='streaks', schema='tracking')
    op.drop_table('streaks', schema='tracking')
    op.drop_index(op.f('ix_tracking_spend_entries_category'), table_name='spend_entries', schema='tracking')
    op.drop_index('idx_spend_household_date', table_name='spend_entries', schema='tracking')
    op.drop_table('spend_entries', schema='tracking')
    op.drop_index('idx_savings_kind', table_name='savings_events', schema='tracking')
    op.drop_index('idx_savings_household_date', table_name='savings_events', schema='tracking')
    op.drop_table('savings_events', schema='tracking')
    op.drop_index('idx_budgets_household_month', table_name='budgets', schema='tracking')
    op.drop_table('budgets', schema='tracking')
    op.drop_index('idx_badge_awards_household', table_name='badge_awards', schema='tracking')
    op.drop_table('badge_awards', schema='tracking')
    op.drop_index(op.f('ix_food_recipes_cuisine'), table_name='recipes', schema='food')
    op.drop_table('recipes', schema='food')
    op.drop_index('idx_receipts_household_date', table_name='receipts', schema='food')
    op.drop_table('receipts', schema='food')
    op.drop_index(op.f('ix_food_pantry_locations_household_id'), table_name='pantry_locations', schema='food')
    op.drop_table('pantry_locations', schema='food')
    op.drop_index(op.f('ix_food_meal_plans_household_id'), table_name='meal_plans', schema='food')
    op.drop_table('meal_plans', schema='food')
    op.drop_table('subscriptions', schema='core')
    op.drop_index('idx_household_members_user', table_name='household_members', schema='core')
    op.drop_table('household_members', schema='core')
    op.drop_index(op.f('ix_core_events_event_type'), table_name='events', schema='core')
    op.drop_index('idx_events_household', table_name='events', schema='core')
    op.drop_index('idx_events_entity', table_name='events', schema='core')
    op.drop_table('events', schema='core')
    op.drop_table('audit_log', schema='core')
    op.drop_index('idx_items_topic_published', table_name='items', schema='content')
    op.drop_index('idx_items_source', table_name='items', schema='content')
    op.drop_index('idx_items_provider_external', table_name='items', schema='content')
    op.drop_table('items', schema='content')
    op.drop_index('idx_ingestion_jobs_status_started', table_name='ingestion_jobs', schema='content')
    op.drop_table('ingestion_jobs', schema='content')
    op.drop_index('idx_conversations_household_recent', table_name='conversations', schema='ai')
    op.drop_table('conversations', schema='ai')
    op.drop_index('idx_briefings_household_date', table_name='briefings', schema='ai')
    op.drop_table('briefings', schema='ai')
    op.drop_index(op.f('ix_tracking_badge_definitions_key'), table_name='badge_definitions', schema='tracking')
    op.drop_table('badge_definitions', schema='tracking')
    op.drop_index('idx_ingredients_canonical', table_name='ingredients', schema='food')
    op.drop_table('ingredients', schema='food')
    op.drop_index(op.f('ix_core_users_email'), table_name='users', schema='core')
    op.drop_table('users', schema='core')
    op.drop_table('households', schema='core')
    op.drop_index(op.f('ix_core_feature_flags_key'), table_name='feature_flags', schema='core')
    op.drop_table('feature_flags', schema='core')
    op.drop_index('idx_sources_provider_kind', table_name='sources', schema='content')
    op.drop_table('sources', schema='content')
    # ### end Alembic commands ###
